[2023-07-12 00:05:01] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 00:22:13] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 00:38:00] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 00:54:28] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 01:09:53] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 01:44:53] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 02:00:18] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 02:17:02] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 02:34:07] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 02:42:51] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 03:01:08] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 03:16:18] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 03:32:29] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 03:50:06] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 04:06:14] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 04:23:52] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 04:56:30] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 05:13:08] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 05:28:34] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 05:44:43] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 06:00:19] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 06:15:49] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 06:31:51] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 06:49:09] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 07:04:53] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 07:22:36] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 07:39:51] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 07:56:28] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 08:12:19] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 08:27:37] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 08:59:52] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 09:17:19] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 09:33:28] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 09:50:58] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 10:07:29] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 10:24:18] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 10:41:49] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 10:59:14] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 11:15:01] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 11:31:29] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 11:49:29] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 12:07:14] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 12:24:44] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 12:42:29] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 13:14:54] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 13:48:19] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 14:04:50] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 14:21:33] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 14:36:40] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 14:53:43] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 15:11:41] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 15:27:59] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 15:43:35] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 16:01:03] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 16:17:32] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 16:35:12] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 16:50:58] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 17:08:13] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 17:23:36] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 17:40:15] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 17:57:21] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 18:13:36] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 18:31:37] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 19:06:38] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 19:22:14] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 19:39:35] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 19:55:52] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 20:11:13] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 20:28:57] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 20:44:29] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 21:02:30] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 21:19:43] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 21:35:05] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 22:09:34] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 22:24:38] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 22:42:05] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 22:57:30] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 23:30:55] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-12 23:48:15] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
